### ISSUE TITLE
ssl certs/private keys

### ISSUE THREAD

**Issue by propyless** [felipe1982/freshmobile#1]
Hello...

I'm not so sure you want to dump your SSL CA Certs and Private Keys with the module.

**Comment by felipe1982** [comment]
Good call

**Comment by propyless** [comment]
just remvoing them won't hide them. you have to rewrite the commit history so that the changes don't exist anymore. either that or delete the repository and upload it without the certs.

**Comment by propyless** [comment]
https://github.com/felipe1982/freshmobile/commit/3c1b71f8805826ac76075eb9dbb5a0f14b52d439

this is what i mean. everyone can still see the file content in the previous commits.
